name: Parse Podcast RSS

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # Agrega el disparador manual

jobs:
  parse_podcast_rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: podcast_parser

      - name: Set remote repository
        uses: actions/checkout@v2
        with:
          repository: geekingzone/geekingzone.github.io.git
          ref: master
          path: website
          token: ${{secrets.ACCESS_TOKEN}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          cd podcast_parser
          python -m pip install --upgrade pip
          pip install feedparser
          pip install beautifulsoup4

      - name: Run Podcast Parser
        run: |
          cd podcast_parser
          python ./parser_script.py
      
      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
        
      - name: Add git files to push
        run: |
          cd website
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automatic commit from GitHub Actions"

      - name: Push Changes to Another Repository
        run: |
          cd website
          git push https://${{ secrets.USER_NAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ secrets.USER_NAME }}/geekingzone.github.io.git
