name: Parse Podcast RSS

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # Agrega el disparador manual

jobs:
  parse_podcast_rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Run Podcast Parser
        run: |
          python ./parser_script.py

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          
      - name: Create Temporary File
        run: |
          echo "Temporary content" > _posts/2023-08-26-hola-caracola.md  # Crear un archivo temporal
          git add _posts
          git commit -m "Automatic commit from GitHub Actions"

      - name: Push Changes to Another Repository
        run: |
          git checkout -b temp-branch
          git push https://${{ secrets.USER_NAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ secrets.USER }}/geekingzone.github.io.git.git temp-branch:main
