name: Parse Podcast RSS

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # Agrega el disparador manual

jobs:
  parse_podcast_rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: podcast_parser

      - name: Set remote repository
        uses: actions/checkout@v2
        with:
          repository: geekingzone/geekingzone.github.io.git
          ref: master
          path: website
          token: ${{secrets.ACCESS_TOKEN}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          cd podcast_parser
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Run Podcast Parser
        run: |
          cd podcast_parser
          python ./parser_script.py
          
      - name: Create Temporary File
        run: |
          pwd
          ls
          cd website
          echo "Temporary content" > _posts/2023-08-26-hola-caracola.md  # Crear un archivo temporal
          git add -A
          git commit -m "Automatic commit from GitHub Actions"

      - name: Push Changes to Another Repository
        run: |
          git push https://${{ secrets.USER_NAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ secrets.USER_NAME }}/geekingzone.github.io.git
